apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          args: ["run", "/scripts/test.js"]
          volumeMounts:
            - name: script
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: k6-script
  backoffLimit: 0
